/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static main.GameWindow.backgroundLabelGameWin;
import static main.GameWindow.backgroundPanel;

/**
 *
 * @author torla
 */
public class MapChooseWindow extends javax.swing.JFrame {

    /**
     * Creates new form MapChooseWindow
     */
    
    static GameWindow game;
    public MapChooseWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mapOneLabel = new javax.swing.JLabel();
        mapTwoLabel = new javax.swing.JLabel();
        mapTreeLabel = new javax.swing.JLabel();
        mapFourLabel = new javax.swing.JLabel();
        mapFiveLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mapOneRadioButton = new javax.swing.JRadioButton();
        mapTwoRadioButton = new javax.swing.JRadioButton();
        mapTreeRadioButton = new javax.swing.JRadioButton();
        mapFourRadioButton = new javax.swing.JRadioButton();
        mapFiveRadioButton = new javax.swing.JRadioButton();
        backgroundLabel = new javax.swing.JLabel();

        buttonGroup1.add(mapFiveRadioButton);
        buttonGroup1.add(mapOneRadioButton);
        buttonGroup1.add(mapTwoRadioButton);
        buttonGroup1.add(mapTreeRadioButton);
        buttonGroup1.add(mapFourRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 780));
        setMinimumSize(new java.awt.Dimension(650, 780));
        setPreferredSize(new java.awt.Dimension(650, 780));
        setResizable(false);

        mapOneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/earthLabel.gif"))); // NOI18N
        mapOneLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapOneLabelMouseClicked(evt);
            }
        });

        mapTwoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/paralelumLabel.gif"))); // NOI18N
        mapTwoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapTwoLabelMouseClicked(evt);
            }
        });

        mapTreeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/pinkLabel.gif"))); // NOI18N
        mapTreeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapTreeLabelMouseClicked(evt);
            }
        });

        mapFourLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/sunLabel.gif"))); // NOI18N
        mapFourLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapFourLabelMouseClicked(evt);
            }
        });

        mapFiveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/blueLabel.gif"))); // NOI18N
        mapFiveLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapFiveLabelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose your map");

        jButton1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton1.setText("PLAY");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mapOneRadioButton.setOpaque(false);
        mapOneRadioButton.setSelected(true);

        mapTwoRadioButton.setOpaque(false);

        mapTreeRadioButton.setOpaque(false);

        mapFourRadioButton.setOpaque(false);

        mapFiveRadioButton.setOpaque(false);

        jLayeredPane1.setLayer(mapOneLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapTwoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapTreeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapFourLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapFiveLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapOneRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapTwoRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapTreeRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapFourRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mapFiveRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(mapTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapTwoRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(mapOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapOneRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(mapFourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mapFourRadioButton))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(mapTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mapTreeRadioButton))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(mapFiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mapFiveRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mapOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(mapOneRadioButton)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mapTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(mapTwoRadioButton)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mapTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(mapTreeRadioButton)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mapFourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(mapFourRadioButton)))
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mapFiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(mapFiveRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/mapChooseProject.gif"))); // NOI18N
        backgroundLabel.setMaximumSize(new java.awt.Dimension(598, 780));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(598, 780));
        backgroundLabel.setPreferredSize(new java.awt.Dimension(598, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        if(mapOneRadioButton.isSelected())
        {
            this.dispose();
            game = new GameWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
            backgroundLabelGameWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/earthProject.gif")));
            
        }else if(mapTwoRadioButton.isSelected())
        {
            this.dispose();
            game = new GameWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
            backgroundLabelGameWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/paralelumProject.gif")));
        }else if(mapTreeRadioButton.isSelected())
        {
            this.dispose();
            game = new GameWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
            backgroundLabelGameWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/pinkProject.gif")));
        }else if(mapFourRadioButton.isSelected())
        {
            this.dispose();
            game = new GameWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
            backgroundLabelGameWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/sunProject.gif")));
        }else if(mapFiveRadioButton.isSelected())
        {
           this.dispose();
            game = new GameWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
            backgroundLabelGameWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/blueProject.gif"))); 
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mapOneLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapOneLabelMouseClicked
        mapOneRadioButton.setSelected(true);
    }//GEN-LAST:event_mapOneLabelMouseClicked

    private void mapTwoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapTwoLabelMouseClicked
        mapTwoRadioButton.setSelected(true);
    }//GEN-LAST:event_mapTwoLabelMouseClicked

    private void mapTreeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapTreeLabelMouseClicked
        mapTreeRadioButton.setSelected(true);
    }//GEN-LAST:event_mapTreeLabelMouseClicked

    private void mapFourLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapFourLabelMouseClicked
        mapFourRadioButton.setSelected(true);
    }//GEN-LAST:event_mapFourLabelMouseClicked

    private void mapFiveLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapFiveLabelMouseClicked
        mapFiveRadioButton.setSelected(true);
    }//GEN-LAST:event_mapFiveLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapChooseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapChooseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapChooseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapChooseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapChooseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel mapFiveLabel;
    private javax.swing.JRadioButton mapFiveRadioButton;
    private javax.swing.JLabel mapFourLabel;
    private javax.swing.JRadioButton mapFourRadioButton;
    private javax.swing.JLabel mapOneLabel;
    private javax.swing.JRadioButton mapOneRadioButton;
    private javax.swing.JLabel mapTreeLabel;
    private javax.swing.JRadioButton mapTreeRadioButton;
    private javax.swing.JLabel mapTwoLabel;
    private javax.swing.JRadioButton mapTwoRadioButton;
    // End of variables declaration//GEN-END:variables
}
