/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import static main.GameWindow.nickNameLabel;
import static main.GameWindow.projectiles;
import static main.GameWindow.timer;

/**
 *
 * @author torla
 */

    
public class StartWindow extends javax.swing.JFrame {

    static String nickName = "";
    
    public StartWindow() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        exitBtn = new javax.swing.JButton();
        newGameBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(598, 780));
        setMinimumSize(new java.awt.Dimension(598, 780));
        setPreferredSize(new java.awt.Dimension(598, 780));
        setResizable(false);
        getContentPane().setLayout(null);

        exitBtn.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setOpaque(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(exitBtn);
        exitBtn.setBounds(190, 510, 230, 44);

        newGameBtn.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        newGameBtn.setText("NEW GAME");
        newGameBtn.setOpaque(false);
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(newGameBtn);
        newGameBtn.setBounds(190, 310, 230, 44);

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter name");
        jLabel2.setFocusable(false);
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(180, 30, 250, 60);

        nameLabel.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameLabel.setOpaque(false);
        nameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLabelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(nameLabel);
        nameLabel.setBounds(170, 100, 270, 60);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(6, 6, 586, 768);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/wallpaper rocket.gif"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(598, 780));
        jLabel1.setMinimumSize(new java.awt.Dimension(598, 780));
        jLabel1.setPreferredSize(new java.awt.Dimension(598, 780));
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 598, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed

        if(!nameLabel.getText().equals(""))
        {
            nickName = nameLabel.getText().toUpperCase();
            this.dispose();
            
            MapChooseWindow game = new MapChooseWindow();
            game.setVisible(true);
            game.setLocationRelativeTo(null);
        }else
        {
            JOptionPane.showMessageDialog(null, "You forget name !", "Error", JOptionPane.ERROR_MESSAGE);
        }


        
        
    }//GEN-LAST:event_newGameBtnActionPerformed

    private void nameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLabelActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nameLabel;
    private javax.swing.JButton newGameBtn;
    // End of variables declaration//GEN-END:variables
}
